# Generated by Django 5.1.4 on 2025-01-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'managed': True},
        ),
    ]
