# Generated by Django 5.1.4 on 2025-01-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_data', '0003_propertysummary_alter_hotel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('property_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review', models.TextField()),
            ],
            options={
                'db_table': 'property_reviews',
            },
        ),
    ]
